urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'MiniMicroBlog.views.home', name='home'),
    # url(r'^MiniMicroBlog/', include('MiniMicroBlog.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^$','microblog.views.login'),
    url(r'^login/$','microblog.views.login'),
    url(r'^logout/$','microblog.views.logout'),
    #url(r'^home/$','microblog.views.loadhome'),
    url(r'^home/(?P<pageindex>\d+)/$','microblog.views.loadhome'),
    #url(r'^square/$','microblog.views.loadsquare'),
    url(r'^square/(?P<pageindex>\d+)/$','microblog.views.loadsquare'),
    url(r'^sysmsg/(?P<pageindex>\d+)/$','microblog.views.loadsysmsg'),
    #url(r'^find/$','microblog.views.loadusers'),
    #url(r'^find/follow/?P<username>[a-zA-Z-_\d]+/$','microblog.views.addfriend'),
    #url(r'^find/unfollow/?P<username>[a-zA-Z-_\d]+/$','microblog.views.deletefriend'),
    url(r'^find/(?P<pageindex>\d+)/$','microblog.views.loadusers'),
    url(r'^register/$','microblog.views.signup'),
    url(r'^register/success/$','django.views.generic.simple.direct_to_template',
        {'template':'prompt/regsuccess.html'}),
    url(r'^reset/$','microblog.views.sendpwd'),
    url(r'^reset/success/$','django.views.generic.simple.direct_to_template',
            {'template':'prompt/resetsuccess.html'}),
    url(r'^help/$','django.views.generic.simple.direct_to_template',
            {'template':'help/aboutweb.html'}),
    url(r'^help/aboutme/$','django.views.generic.simple.direct_to_template',
            {'template':'help/aboutme.html'}),
    url(r'^help/webstate/$','django.views.generic.simple.direct_to_template',
            {'template':'help/webstate.html'}),
    url(r'^user/leavemsg/$','microblog.views.leavemsg'),
    url(r'^user/publish/$','microblog.views.publish'),
    url(r'^user/setting/$','microblog.views.setting'),
    url(r'^user/changepwd/$','microblog.views.changepwd'),
    url(r'^user/follow/(?P<pageindex>\d+)/$','microblog.views.loadfollowuser'),
    url(r'^user/(?P<username>[\w_\d]+)/(?P<pageindex>\d+)/$','microblog.views.loadusershuoshuo'),
    url(r'^message/(?P<ssid>\d+)/$','microblog.views.ssdetail'),
    url(r'^detailsysmsg/(?P<sysmsgid>\d+)/$','microblog.views.sysmsgdetail'),
    url(r'^prompt/(?P<way>\bfollow\b)/(?P<param>[\w_\d]+)/$','microblog.views.systeminfo'),
    url(r'^prompt/(?P<way>\bunfollow\b)/(?P<param>[\w_\d]+)/$','microblog.views.systeminfo'),
    url(r'^prompt/(?P<way>\bdelshuoshuo\b)/(?P<param>[\w_\d]+)/$','microblog.views.systeminfo'),
    url(r'^prompt/(?P<way>\bdelsysmsg\b)/(?P<param>[\w_\d]+)/$','microblog.views.systeminfo'),
    url(r'^admin/', include(admin.site.urls)),
    #url(r'^comments/',include('django.contrib.comments.urls')),
    url(r'captcha/',include('captcha.urls')),
)

microblog/models.py
# -*- coding: utf-8 -*-
from django.db import models
import time
from django.utils import timesince,html
from MiniMicroBlog.settings import *
import PIL
from StringIO import StringIO
from MiniMicroBlog.utils import formatter,encrypt

from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic
from django.db.models import signals
from django.dispatch import dispatcher


class PostWay(models.Model):
    name = models.CharField('方式名称',max_length=20)

    def __unicode__(self):
        return self.name

    def save(self):
        return super(PostWay,self).save()

    class Meta:
        verbose_name='分类'
        verbose_name_plural='分类'


class Status(models.Model):
    kind = models.CharField('消息状态',max_length=20)

    def __unicode__(self):
        return self.kind

    def save(self):
        return super(Status,self).save()

    class Meta:
        verbose_name='消息状态'
        verbose_name_plural='消息状态'


class User(models.Model):
    username=models.CharField('用户名',max_length=20)
    userpwd=models.CharField('密码',max_length=50)
    realname=models.CharField('姓名',max_length=20)
    email=models.EmailField('邮件')
    photo=models.ImageField('头像',upload_to='face/%Y/*m/%d',default='',blank=True)
    url=models.CharField('个人主页',max_length=100,default='',blank=True)
    aboutme=models.TextField('关于我',max_length=500,default='',blank=True)
    #about_me=models.TextField('(详)关于我',max_length=500,default='',blank=True)
    regtime=models.DateTimeField('注册时间',auto_now=True)
    friend=models.ManyToManyField('self',verbose_name='朋友')

    def __unicode__(self):
        return self.username

    def formattime(self):
        return self.regtime.strftime('%Y-%m-%d %H:M:%S')

    def shortcut(self):
        return formatter.substr(self.aboutme,20)

    def save(self,modify_pwd=True):
        return super(User,self).save()

    class Meta:
        verbose_name=u'用户'
        verbose_name_plural=u'用户'




class Shuoshuo(models.Model):
    message=models.TextField('消息',max_length=500)
    uptime=models.DateTimeField('发布时间',auto_now=True)
    postway=models.ForeignKey(PostWay,verbose_name='方式')
    user=models.ForeignKey(User,verbose_name='发布人')

    events=generic.GenericRelation('Event')

    def __unicode__(self):
        return self.message

    def description(self):
        return u'你的好友 %s 发表了说说"%s"' % (self.user.username,self.message)

    def shortcut(self):
        return formatter.substr(self.message,30)

    def fomattime(self):
        return self.uptime.strftime('%Y-%m-%d %H:%M:%S')

    def postwayname(self):
        return self.postway.name

    def username(self):
        return self.user.username

    def save(self):
        self.message=formatter.contentTinyUrl(self.message)
        self.message=html.escape(self.message)
        super(Shuoshuo,self).save()

    class Meta:
        verbose_name=u'说说'
        verbose_name_plural=u'说说'

class Comment(models.Model):
    comment=models.TextField('留言',max_length=500)
    uptime=models.DateTimeField('留言时间',auto_now=True)
    shuoshuo=models.ForeignKey(Shuoshuo,verbose_name='说说')
    user=models.ForeignKey(User,verbose_name='留言人')

    def __unicode__(self):
        return self.comment

    def shortcut(self):
        return formatter.substr(self.comment,30)

    def fomattime(self):
        return self.uptime.strftime('%Y-%m-%d %H:%M:%S')

    def username(self):
        return self.user.username

    def save(self):
        self.comment=formatter.contentTinyUrl(self.comment)
        self.comment=html.escape(self.comment)
        super(Comment,self).save()

    class Meta:
        verbose_name=u'留言'
        verbose_name_plural=u'留言'


class MsgText(models.Model):
    user=models.ForeignKey(User,verbose_name='发送人')
    msgtext=models.TextField('内容',max_length=500,blank=False)
    sendtime=models.DateTimeField('发送时间',auto_now=True)

    def __unicode__(self):
        return self.msgtext

    def senduser(self):
        return self.user.username

    def save(self):
        return super(MsgText,self).save()

    class Meta:
        verbose_name=u'消息内容'
        verbose_name_plural=u'消息内容'


class Message(models.Model):
    user=models.ForeignKey(User,verbose_name='收信人')
    msgtext=models.ForeignKey(MsgText,verbose_name='消息内容')
    status=models.ForeignKey(Status,verbose_name='状态')

    def __unicode__(self):
        return self.user.username

    def recvuser(self):
        return self.user.username

    def kind(self):
        return  self.status.kind

    def message(self):
        return self.msgtext.msgtext

    def save(self):
        return super(Message,self).save()

    class Meta:
        verbose_name=u'消息'
        verbose_name_plural=u'消息'


class Event(models.Model):
    '''
    class ContentType(models.Model):
        name=models.CharField(max_length=100)
        app_label=models.CharField(max_length=100)
        model=models.CharField(_('python model class name'),max_length=100)
        objects=ContentTypeManager()
    '''
    user=models.ForeignKey(User)
    content_type=models.ForeignKey(ContentType)
    object_id=models.PositiveIntegerField()
    event=generic.GenericForeignKey('content_type','object_id')
    created=models.DateTimeField(u'说说发表时间',auto_now_add=True)

    def __unicode__(self):
        return u'%s的说说：%s'% (self.user,self.description())

    def description(self):
        return self.event.description()


#def shuoshuo_save(sender,instance,signal,*args,**kwargs):
def shuoshuo_save(sender,instance,created,*args,**kwargs):
    shuoshuo=instance
    #if (shuoshuo.updated-shuoshuo.created).seconds <1:
    if created:
        event=Event(user=shuoshuo.user,event=shuoshuo)
        #time.sleep(0.1)
        event.save()

#dispatcher.connect(shuoshuo_save,signal=signals.post_save,sender=Shuoshuo)
signals.post_save.connect(shuoshuo_save,sender=Shuoshuo)

microblog/forms.py
#-*- coding:utf-8 -*-

from django import  forms
from captcha.fields import CaptchaField
from microblog.models import User
from utils import encrypt
import re

class RegistForm(forms.Form):
    username=forms.CharField(max_length=20,label=('昵称(必填)'),required=True)
    realname=forms.CharField(max_length=20,label=('真实姓名(必填)'),required=True)
    email=forms.EmailField(label=('邮箱(必填)'),required=True)
    password=forms.CharField(label='密码',widget=forms.PasswordInput(),required=True)
    checkpassword=forms.CharField(label='确认密码',widget=forms.PasswordInput(),required=True)

    def clean_username(self):
        username=self.cleaned_data['username']
        if not re.search(r'^\w+$',username):
            raise forms.ValidationError(u'用户名只能包含字母数字和下划线！')
        if User.objects.filter(username=username):
            raise forms.ValidationError(u'用户名已经存在！')
        return username

    def clean_email(self):
        email=self.cleaned_data['email']
        if User.objects.filter(email=email):
            raise forms.ValidationError(u'此邮箱已注册！')
        return email

    def clean_checkpassword(self):
        password=self.cleaned_data.get('password',None)
        checkpassword=self.cleaned_data.get('checkpassword',None)
        pwdlength=len(password)
        if pwdlength < 6:
            raise forms.ValidationError(u'密码不能少于6位！')
        if password!=checkpassword:
            raise forms.ValidationError(u'密码不匹配！')
        return password


class LoginForm(forms.Form):
    username=forms.CharField(max_length=20,label=('用户名'),required=True)
    password=forms.CharField(label='密码',widget=forms.PasswordInput(),required=True)

    def clean_username(self):
        username=self.cleaned_data['username']
        if not User.objects.filter(username=username):
            raise forms.ValidationError(u'用户名不存在存在！注册否？')
        return username

    def clean_password(self):
        username=self.cleaned_data.get('username','')
        password=encrypt.encodeMD5(self.cleaned_data['password'])
        if User.objects.filter(username=username):
            if password != User.objects.get(username=username).userpwd:
                raise forms.ValidationError(u'密码错误！')
        return ""


class ChangePwdForm(forms.Form):
    oldpassword=forms.CharField(label='旧密码',widget=forms.PasswordInput(),required=True)
    newpassword=forms.CharField(label='新密码',widget=forms.PasswordInput(),required=True)
    checkpassword=forms.CharField(label='确认密码',widget=forms.PasswordInput(),required=True)

    def clean_data(self):
        oldpassword=self.cleaned_data['oldpassword']
        newpassword=self.cleaned_data['newpassword']
        checkpassword=self.cleaned_data['checkpassword']
        lenpwd=len(newpassword)
        if lenpwd <6:
            raise forms.ValidationError(u'密码不能少于6位！')

class ResetForm(forms.Form):
    email=forms.EmailField(label='Email:',required=True)

    def clean_email(self):
        email=self.cleaned_data['email']
        if not User.objects.filter(email=email):
            raise forms.ValidationError(u'对不起，不存在这样的邮箱，你再想想！')
        return email

templates/microblog/commentlist.html

{% load usertags %}
{% include "microblog/commentitem.html" %}
<div class="msg">
    <form action='/user/leavemsg/' method='post'>
        <p><textarea id="id_comment" rows="5" cols="110" name="comment"></textarea></p>
        <input value="{{ shuoshuo.id }}" name="ssid" type="hidden">
        <p><input tabindex="11" type="submit" class="formbutton" value="回复"></p>
    </form>
</div>

templates/microblog/findwho.html
{% extends "base/base.html" %}
{% block content %}
    <table id="columns">
        <tbody>
        <tr>
            <td id="main">
                <div id="header">
                    <h2 >你想找谁？</h2>
                </div>
                <div id="content">
                    <div id="stream" class="message"><ol class="wa solo"></ol>
                        {% include "microblog/userlist.html" %}
                    </div>
                    {% include "sidebar/pagebar.html" %}
                </div>
            </td>
            {% include "sidebar/sidebar.html" %}
        </tr>
        </tbody>
    </table>
{% endblock %}

templates/microblog/followlist.html
<ol class="wa">
{% if not friendlist %}
    <li class="unlight">
        <p>你现在一个关注的人都木有，打算怎么办呢？赶紧出发吧！</p>
    </li>
{% else %}
    {% for item in friendlist %}
        <li class="unlight">
            {% include "microblog/useritem.html" %}
        </li>
    {% endfor %}
{% endif %}
</ol>

templates/microblog/followuser.html
{% extends "base/base.html" %}
{% block content %}
    <table id="columns">
        <tbody>
        <tr>
            <td id="main">
                <div id="header">
                    <h2 >看看我关注的帅哥靓妹</h2>
                </div>
                <div id="content">
                    <div id="stream" class="message"><ol class="wa solo"></ol>
                        {% include "microblog/followlist.html" %}
                    </div>
                    {% if friendlist %}
                    {% include "sidebar/pagebar.html" %}
                    {% endif %}
                </div>
            </td>
            {% include "sidebar/sidebar.html" %}
        </tr>
        </tbody>
    </table>
{% endblock %}

templates/microblog/home.html
{% extends "base/base.html" %}
{% block content %}
<table id="columns">
    <tbody>
        <tr>
            <td id="main">
                <div id="header">
                    <h2 >我的家园</h2>
                </div>
                <div id="content">
                    <div id="stream" class="message"><ol class="wa solo"></ol></div>
                    {% include "microblog/publish.html" %}
                    <div id="stream" class="message">
                    {% include "microblog/shuoshuolist.html" %}
                    </div>
                    {% include "sidebar/pagebar.html" %}
                </div>
            </td>
                {% include "sidebar/sidebar.html" %}
        </tr>
    </tbody>
</table>
{% endblock %}

templates/microblog/listitem.html
{% load usertags %}
<span>
    <a class="avatar" href="/user/{{ item.user.username }}/1/" ><img src="{{ item.user.photo|photo }}" width="41px" height="41px" title="{{ item.user.username }}" /></a>
    <a href="{{ item.user.url }}" class="author">{{ item.user.realname }}</a>
</span>
<span class="content">{{ item.message }}<a href="/message/{{ item.id }}">more...</a></span>
<span class="stamp">
    {{ item.uptime|timesince }}前，
    <span class="method">
        通过 {{ item.postway.name }}
    </span>
    {% ifequal item.user.id userinfo.id %}
    <span><a href="/prompt/delshuoshuo/{{ item.id }}/"> 删除</a></span>
    {% endifequal %}
</span>

templates/microblog/publish.html
<div id="publish">
    <form method="post" action="/user/publish/">
        <p>
            想说点什么呢？
        </p>
        <p>
            <textarea name="message" class="text" rows="5" cols="75"></textarea>
        </p>
        <p>
            {% for i in error.values %}
                {{ i }}
            {% endfor %}
        </p>
        <p class="act">
            <input tabindex="11" type="submit" class="formbutton" value="发表">
        </p>
    </form>
</div>

templates/microblog/square.html
{% extends "base/base.html" %}
{% block content %}
    <table id="columns">
        <tbody>
        <tr>
            <td id="main">
                <div id="header">
                    <h2 >看看别人在做什么</h2>
                </div>
                <div id="content">
                    <div id="stream" class="message"><ol class="wa solo"></ol>
                    {% include "microblog/shuoshuolist.html" %}
                    </div>
                    {% include "sidebar/pagebar.html" %}
                </div>
            </td>
            {% include "sidebar/sidebar.html" %}
        </tr>
        </tbody>
    </table>
{% endblock %}

templates/microblog/sysmsgdetail.html
{% extends "base/base.html" %}
{% load usertags %}
{% block content %}
    <div id="body" class="narrowlook ui-roundedbox" style="margin-top: 1em;padding-bottom: 1.5em;">
        <div id="topbox" class="ui-roundedbox-content" style="padding: 25px 15px 10px;">
            <div id="info">
                <div id="avatar">
                    <a href="#"><img src="{{ sysmsg.user.photo|photo }}" class="msgat" title="{{ sysmsg.user.username }}"></a>
                </div>
                <div id="latest" class="msg">
                    <h1>公告人：
                        <a href="#">
                           {{ sysmsg.user.username }}
                        </a>
                    </h1>
                    <h2>
                        <span class="content">
                            {{ sysmsg.msgtext }}
                        </span>
                        <span class="stamp">
                            {{ sysmsg.sendtime|date }}
                        </span>
                    </h2>
                </div>
            </div>
        </div>
        <div class="bottombox"></div>
    </div>
{% endblock %}

templates/microblog/sysmsglist.html
<ol class="wa">
    {% if list %}
        {% for item in list %}
            <li class="unlight">
                {% include "microblog/sysitem.html" %}
            </li>
        {% endfor %}
    {% else %}
        <li class="unlight">
            <p>暂且还没有新的通知公告，有了的话会告诉你的哦！</p>
        </li>
    {% endif %}
</ol>

templates/microblog/systeminfo.html
{% extends "base/base.html" %}
{% block content %}
    <table id="columns">
        <tbody>
        <tr>
            <td id="main">
                <div id="phupdate">
                    <h2 >友情提示</h2>
                    <div class="act">
                    </div>
                </div>
                <div id="content">
                    <div id="stream" class="message"><ol class="wa solo"></ol></div>
                    <p>
                        {{ message }}
                    </p>
                </div>
                </div>
            </td>
            {% include "sidebar/sidebar.html" %}
        </tr>
        </tbody>
    </table>
{% endblock %}

templates/microblog/systemmsg.html
{% extends "base/base.html" %}
{% block content %}
    <table id="columns">
        <tbody>
        <tr>
            <td id="main">
                <div id="header">
                    <h2 >系统公告</h2>
                </div>
                <div id="content">
                    <div id="stream" class="message"><ol class="wa solo"></ol>
                        {% include "microblog/sysmsglist.html" %}
                    </div>
                    {% include "sidebar/pagebar.html" %}
                </div>
            </td>
            {% include "sidebar/sidebar.html" %}
        </tr>
        </tbody>
    </table>
{% endblock %}

templates/microblog/useritem.html
{% load usertags %}
{% load relationtags %}
<a class="avatar" href="/user/{{ item.username }}/1/" ><img src="{{ item.photo|photo }}" width="41px" height="41px" title="{{ item.username }}" /></a>
<a href="{{ item.url }}" class="name">{{ item.username }}</a>
<p class="location">
    所在地：
    <span class="region">
        Xsank的小站
    </span>
</p>
<p class="lastmsg">
    {{ item.aboutme }}
</p>
<p class="actions">
    {% if item|inrelation:friendlist %}
        <a href="/prompt/unfollow/{{ item.username }}/" title="{{ item.username }}" class="post_act bh">取消关注</a>
    {% else %}
        <a href="/prompt/follow/{{ item.username }}/" title="{{ item.username }}" class="post_act bh">关注此人</a>
    {% endif %}
</p>

templates/microblog/userlist.html
<ol class="wa">
    {% for item in userlist %}
        <li class="unlight">
            {% include "microblog/useritem.html" %}
        </li>
    {% endfor %}
</ol>